### ISSUE TITLE
Import Error:This platform lacks a functioning sem_open implementation, therefore, the required synchronization primitives needed will not function, see issue 3770.

### ISSUE THREAD

**Issue by wzh420** [WikiExtractor/wikiextractor#90]
Python 2.7.3 

WikiExtractor.py zhwiki-latest-pages-articles.xml -o wikiextractor-output                                                    
INFO: Loaded 0 templates in 0.0s
INFO: Starting page extraction from zhwiki-latest-pages-articles.xml.
Traceback (most recent call last):
  File "/home/work/.jumbo/bin/WikiExtractor.py", line 4, in <module>
    __import__('pkg_resources').run_script('wikiextractor==2.66', 'WikiExtractor.py')
  File "/home/work/.jumbo/lib/python2.7/site-packages/pkg_resources/__init__.py", line 729, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/home/work/.jumbo/lib/python2.7/site-packages/pkg_resources/__init__.py", line 1649, in run_script
    exec(script_code, namespace, namespace)
  File "/home/work/.jumbo/lib/python2.7/site-packages/wikiextractor-2.66-py2.7.egg/EGG-INFO/scripts/WikiExtractor.py", line 3047, in <module>
    
  File "/home/work/.jumbo/lib/python2.7/site-packages/wikiextractor-2.66-py2.7.egg/EGG-INFO/scripts/WikiExtractor.py", line 3043, in main
    
  File "/home/work/.jumbo/lib/python2.7/site-packages/wikiextractor-2.66-py2.7.egg/EGG-INFO/scripts/WikiExtractor.py", line 2763, in process_dump
    
  File "/home/work/.jumbo/lib/python2.7/multiprocessing/__init__.py", line 217, in Queue
    from multiprocessing.queues import Queue
  File "/home/work/.jumbo/lib/python2.7/multiprocessing/queues.py", line 48, in <module>
    from multiprocessing.synchronize import Lock, BoundedSemaphore, Semaphore, Condition
  File "/home/work/.jumbo/lib/python2.7/multiprocessing/synchronize.py", line 59, in <module>
    " function, see issue 3770.")
ImportError: This platform lacks a functioning sem_open implementation, therefore, the required synchronization primitives needed will not function, see issue 3770.

**Comment by attardi** [comment]
Which platform are you using?
If possible, use linux.
